# Generated by Django 3.0.2 on 2020-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0004_auto_20200118_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='word',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
