# Generated by Django 3.0.2 on 2020-01-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0005_diary_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='center',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
