# Generated by Django 3.0.2 on 2020-01-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0006_reserve_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_chat',
            name='userId',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
