# Generated by Django 3.0.2 on 2020-01-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0008_auto_20200121_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='age',
            field=models.CharField(blank=True, default='20200120', max_length=8, null=True),
        ),
    ]
