# Generated by Django 3.0.2 on 2020-01-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0009_auto_20200121_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='center',
            field=models.CharField(choices=[('cnu_student', '충남대학교 학생상담센터'), ('cnu_self', '심리성장과 자기조절센터')], default='None', max_length=100),
        ),
    ]
