# Generated by Django 3.0.2 on 2020-01-21 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banana', '0010_auto_20200121_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_chat',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
