# Generated by Django 3.0.2 on 2020-01-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0014_auto_20200121_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_chat',
            name='userId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
